# Generated by Django 5.0.3 on 2024-03-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_todo_completed_alter_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
